import pptxgen from "pptxgenjs";

const COLORS = {
    primary: "1E3A8A",      // Dark Blue
    secondary: "0F172A",    // Dark Slate
    white: "FFFFFF",        // White
    border: "D1D5DB",       // Light Gray
    text: "111827",         // Dark Gray Text
    muted: "6B7280"         // Muted Gray
};

export const generatePpt = async (data) => {
    const ppt = new pptxgen();
    ppt.layout = "LAYOUT_WIDE";
    ppt.author = "MultiMind";
    ppt.title = data.title;
    ppt.subject = data.title;
    ppt.company = "MultiMind";

    ppt.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos",
    };

    // Add cover slide
    addCover(ppt, data);

    // Add content slides
    data?.slides?.forEach((s, i) => {
        addContentSlide(
            ppt,
            s.title,
            s.points,
            i + 1,
            data.slides.length
        );
    });

    // Add thank you slide
    addThankYou(ppt);
    return ppt;
};

const addCover = (ppt, data) => {
    const slide = ppt.addSlide();
    slide.background = {
        color: COLORS.primary
    };
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: {
            color: "60A5FA"
        },
        line: {
            color: "60A5FA"
        }
    });
    slide.addText(data.title, {
        x: 1,
        y: 2.8,
        w: 11.5,
        h: 1.5,
        align: "center",
        color: "FFFFFF",
        fontSize: 36,
        bold: true
    });

    slide.addText(data.subtitle || "", {
        x: 1,
        y: 4.5,
        w: 11.5,
        h: 0.5,
        align: "center",
        color: "DBEAFE",
        fontSize: 18,
    });

    slide.addText("Generated By MultiMind", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "BFDBFE",
        fontSize: 10,
    });
};

const addContentSlide = (ppt, title, points, page, total) => {
    const slide = ppt.addSlide();
    slide.background = {
        color: COLORS.white
    };

    slide.addText(title, {
        x: 0.7,
        y: 0.4,
        w: 12,
        h: 0.6,
        align: "left",
        color: COLORS.primary,
        bold: true,
        fontSize: 24,
    });

    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 1.1,
        w: 12,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1.2
        },
    });

    const visiblePoints = points.slice(0, 6);
    visiblePoints.forEach((point, index) => {
        const y = 1.4 + index * 0.85;
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.65,
            fill: {
                color: page % 2 ? "F8FAFC" : "EFF6FF",
            },
            line: {
                color: COLORS.border,
            },
            radius: 0.08,
        });
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.92,
            y: y + 0.24,
            w: 0.12,
            h: 0.12,
            fill: {
                color: COLORS.primary,
            },
            line: {
                color: COLORS.primary,
            },
        });

        slide.addText(point, {
            x: 1.2,
            y: y + 0.15,
            w: 11,
            h: 0.4,
            fontSize: 15,
            color: COLORS.text,
            fit: "shrink",
        });
    });

    slide.addText(`${page}/${total}`, {
        x: 12.1,
        y: 6.9,
        w: 0.8,
        h: 0.2,
        align: "right",
        fontSize: 10,
        color: COLORS.muted,
    });
    
    slide.addText(`MultiMind`, {
        x: 0.6,
        y: 6.9,
        w: 2,
        h: 0.2,
        fontSize: 10,
        color: COLORS.muted,
    });
};

const addThankYou = (ppt) => {
    const slide = ppt.addSlide();
    slide.background = {
        color: COLORS.secondary,
    };
    slide.addText(`Thank You`, {
        x: 0,
        y: 2.8,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        fontSize: 40,
        bold: true,
    });
    slide.addText(`Generated by MultiMind`, {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
    });
};
